export const GameConfig = Object.freeze({
  initialPhysicsMode: "classic",
  canvas: {
    width: 960,
    height: 576,
    tileSize: 32,
  },
  physics: {
    groundAcceleration: 0.52,
    airAcceleration: 0.34,
    groundFriction: 0.82,
    airFriction: 0.96,
    maxRunSpeed: 3.85,
    jumpVelocity: -10.8,
    springVelocity: -8.4,
    springPadCompression: 16,
    springPadPressSpeed: 0.8,
    springPadReleaseSpeed: 0.5,
    gravity: 0.48,
    fastFallGravity: 0.36,
    maxFallSpeed: 12.5,
    wallJumpVelocityX: 5.4,
    wallJumpVelocityY: -10.4,
    wallClimbJumpVelocityX: 1.2,
    wallClimbJumpVelocityY: -9.2,
    wallGripFrames: 90,
    wallGripFallSpeed: 0.22,
    wallSlideSpeed: 1.65,
    wallLatchControlLockFrames: 30,
  },
  physicsProfiles: {
    classic: {
      label: "Классика",
      groundAcceleration: 0.52,
      airAcceleration: 0.34,
      groundFriction: 0.82,
      airFriction: 0.96,
      maxRunSpeed: 3.85,
      maxHorizontalSpeed: 3.85,
      jumpVelocity: -10.8,
      jumpHoldFrames: 0,
      jumpHoldForce: 0,
      gravity: 0.48,
      fastFallGravity: 0.36,
      maxFallSpeed: 12.5,
      wallJumpMomentumCarry: 0,
      wallJumpAwayBoost: 0,
      wallJumpTowardScale: 1,
      wallJumpTowardUpBoost: 0,
      sameWallRelatchFrames: null,
      lockWallOnLatch: true,
      wallJumpVelocityX: 5.4,
      wallJumpVelocityY: -10.4,
      wallClimbJumpVelocityX: 1.2,
      wallClimbJumpVelocityY: -9.2,
      wallGripFrames: 90,
      wallGripFallSpeed: 0.22,
      wallSlideSpeed: 1.65,
      wallFriction: 0,
      wallLatchControlLockFrames: 30,
    },
    nplus: {
      label: "N+ мод",
      groundAcceleration: 0.15,
      airAcceleration: 0.08,
      groundFriction: 0.94,
      airFriction: 0.988,
      turnFriction: 0.975,
      maxRunSpeed: 4.45,
      maxHorizontalSpeed: 5.55,
      jumpVelocity: -7.35,
      jumpHoldFrames: 42,
      jumpHoldForce: 0.14,
      jumpHoldForceEnd: 0.035,
      jumpHoldDecay: 1.35,
      jumpReleaseGravity: 0.11,
      gravity: 0.36,
      fastFallGravity: 0.24,
      maxFallSpeed: 11.4,
      wallJumpVelocityX: 4.35,
      wallJumpVelocityY: -7.8,
      wallClimbJumpVelocityX: 0.82,
      wallClimbJumpVelocityY: -8.15,
      wallJumpMomentumCarry: 0.42,
      wallJumpAwayBoost: 0.85,
      wallJumpTowardScale: 0.72,
      wallJumpTowardUpBoost: -0.45,
      sameWallRelatchFrames: 14,
      lockWallOnLatch: false,
      wallGripFrames: 120,
      wallGripFallSpeed: 0.14,
      wallSlideSpeed: 1.65,
      wallFriction: 0.38,
      wallLatchControlLockFrames: 30,
    },
    moon: {
      label: "Лунный мод",
      groundAcceleration: 0.075,
      airAcceleration: 0.24,
      groundFriction: 0.965,
      airFriction: 0.9994,
      turnFriction: 0.995,
      maxRunSpeed: 3.35,
      maxHorizontalSpeed: 8.2,
      jumpVelocity: -4.25,
      jumpHoldFrames: 124,
      jumpHoldForce: 0.058,
      jumpHoldForceEnd: 0.024,
      jumpHoldDecay: 0.82,
      jumpReleaseGravity: 0.018,
      gravity: 0.09,
      fastFallGravity: 0.08,
      maxFallSpeed: 4.8,
      wallJumpVelocityX: 2.85,
      wallJumpVelocityY: -5.2,
      wallClimbJumpVelocityX: 0.42,
      wallClimbJumpVelocityY: -5.65,
      wallJumpMomentumCarry: 0.72,
      wallJumpAwayBoost: 0.35,
      wallJumpTowardScale: 0.35,
      wallJumpTowardUpBoost: 0,
      sameWallRelatchFrames: 24,
      lockWallOnLatch: false,
      wallGripFrames: 150,
      wallGripFallSpeed: 0.055,
      wallSlideSpeed: 0.65,
      wallFriction: 0.5,
      wallLatchControlLockFrames: 30,
    },
  },
  player: {
    width: 22,
    height: 27,
  },
  timing: {
    respawnMs: 560,
    deathFreezeFrames: 26,
    hintIntervalMs: 9000,
  },
  performance: {
    debugOverlay: false,
    longFrameMs: 24,
    historySize: 120,
    fpsOptions: [30, 60, 120, 165],
    initialFpsCap: 165,
  },
  camera: {
    deadZoneWidth: 250,
    deadZoneHeight: 150,
  },
});
